services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abac_scud_web
    env_file:
      - .env
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: "5432"
      DJANGO_ALLOWED_HOSTS: 127.0.0.1,localhost,0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
